Repository CampusDelSaber/hermes, pull requests merged in 2023-07, with the labels that each got.

#230 bug-fix:fixing the bug of a new confirmation pop up when cancelling t…
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpConfirmIncidentCanceling.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
Labels: bugfix

#228 bug-fix:fixing the bug reset default when incident cancelled
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
Labels: bugfix

#233 fix: Bug 232 - cancel navigation button crashing the app
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
Labels: bugfix

#229 Bug-fixed:Current location ignored in filters
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/FilterCategoriesController.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: bugfix

#237 Bug Fix/ ID-506 & ID-509/ Incorrect format of username and full name text fields in account information
  app/src/main/res/layout/activity_account_information.xml
  app/src/main/res/values/strings.xml
Labels: bug, Severity 3

#227 bug-fixing: incorrect dialog displayed solved
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
Labels: bugfix

#239 Bug/id 234/recalculate route button generates new route from incorrect start point
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/model/Utils/MapPolyline.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/distance_and_time_view.xml
  app/src/main/res/values/strings.xml
Labels: bugfix

#221 BugFix: Decomposed estimation time
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/PolylineRouteUpdaterController.java
  app/src/main/java/com/isc/hermes/model/navigation/LiveRouteEstimationsWorker.java
  app/src/main/java/com/isc/hermes/model/navigation/NavigationRouteParser.java
  app/src/main/java/com/isc/hermes/model/navigation/NavigationTrackerTools.java
  app/src/main/java/com/isc/hermes/model/navigation/RouteDistanceHandler.java
  app/src/main/java/com/isc/hermes/model/navigation/RouteEstimatesManager.java
  app/src/main/java/com/isc/hermes/model/navigation/RouteSegmentRecord.java
  app/src/main/java/com/isc/hermes/model/navigation/TrackRecoveryHandler.java
  app/src/main/java/com/isc/hermes/model/navigation/UserLocationTracker.java
  app/src/main/java/com/isc/hermes/model/navigation/UserOutsideRouteException.java
  app/src/main/java/com/isc/hermes/model/navigation/UserRouteTracker.java
  app/src/main/java/com/isc/hermes/model/navigation/exceptions/RouteOutOfTracksException.java
  app/src/main/java/com/isc/hermes/utils/CoordinatesDistanceCalculator.java
  app/src/main/java/com/isc/hermes/view/GenerateRandomIncidentView.java
Labels: bugfix

#243 Bug/id 173/error report traffics point the information saving
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/ShowTrafficController.java
  app/src/main/java/com/isc/hermes/controller/TrafficAutomaticFormController.java
  app/src/main/java/com/isc/hermes/controller/ViewIncidentsController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/database/TrafficUploader.java
  app/src/main/java/com/isc/hermes/model/navigation/LiveRouteEstimationsWorker.java
  app/src/main/java/com/isc/hermes/model/navigation/RouteEstimatesManager.java
  app/src/test/java/com/isc/hermes/trafficAutomatic/TrafficAutomaticTest.java
Labels: bugfix

#242 fix-bug:fixing the validations of the incidents form
  app/src/main/java/com/isc/hermes/controller/IncidentDialogController.java
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
Labels: bug, enhancement

#241 Bug-ID/195 - Application stops when the user selects a filter to mark points of interest without internet connection on the main activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/FilterCategoriesController.java
  app/src/main/java/com/isc/hermes/controller/FilterController.java
  app/src/main/java/com/isc/hermes/controller/IncidentDialogController.java
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/ShowTrafficController.java
  app/src/main/java/com/isc/hermes/controller/TrafficAutomaticFormController.java
  app/src/main/java/com/isc/hermes/controller/ViewIncidentsController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/database/TrafficUploader.java
  app/src/main/java/com/isc/hermes/model/navigation/LiveRouteEstimationsWorker.java
  app/src/main/java/com/isc/hermes/model/navigation/RouteEstimatesManager.java
  app/src/main/java/com/isc/hermes/utils/AndroidRequestActivation.java
  app/src/main/java/com/isc/hermes/utils/AndroidServicesVerification.java
  app/src/main/java/com/isc/hermes/utils/NetworkChangeReceiver.java
  app/src/main/java/com/isc/hermes/utils/OnNetworkChangeListener.java
  app/src/main/java/com/isc/hermes/view/FiltersView.java
  app/src/main/res/layout/activity_main.xml
  app/src/test/java/com/isc/hermes/trafficAutomatic/TrafficAutomaticTest.java
Labels: bugfix

#247 bug 224 solved
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/MapWayPointController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
Labels: bugfix

#245 Bug/ ID-484/ Missing Error Message For SignUp/SignIn Withou tInternet Access
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
Labels: bug, Severity 4

#258 Resizing of the filter view was modified for a better user experience.
  app/src/main/res/layout/activity_main.xml
Labels: bug

#254 issue #163 solved
  app/src/main/java/com/isc/hermes/controller/ViewIncidentsController.java
Labels: bugfix

#256 Bug/ID-172/NoMessageIsDisplayedIfIDoNotHaveMyLocationActivatedForTheCurrentLocation
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
Labels: bugfix

#265 Bug/ID-222/Menu with non-existent functionalities
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/res/menu/lateral_dropdown_menu.xml
Labels: bug, Severity 3

#263 Bug/id 208/search engine fails to provide relevant suggestions for misspelled keywords
  app/src/main/java/com/isc/hermes/model/Searcher.java
Labels: bugfix

#259 Bugs(ID-216/ID-257) /App crashes when start and destination points are set to the same location and cancel option bug
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/MapWayPointController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/res/drawable/arrow_nav.png
  app/src/main/res/layout/navigation_options.xml
  app/src/main/res/values/strings.xml
Labels: Severity 1, bugfix

#262 Bug/id 516/overlapping polygons
  app/src/main/java/com/isc/hermes/controller/GenerateRandomIncidentController.java
  app/src/main/java/com/isc/hermes/controller/MapPolygonController.java
  app/src/main/java/com/isc/hermes/controller/PolygonVisualizationController.java
  app/src/main/java/com/isc/hermes/controller/ViewIncidentsController.java
  app/src/main/java/com/isc/hermes/generators/IncidentGenerator.java
  app/src/main/java/com/isc/hermes/generators/PolygonGenerator.java
  app/src/main/java/com/isc/hermes/generators/RandomGenerator.java
  app/src/main/java/com/isc/hermes/model/incidentsRequesting/NaturalDisasterRequesting.java
  app/src/main/java/com/isc/hermes/requests/incidents/PolygonRequester.java
  app/src/main/java/com/isc/hermes/view/MapPolygonStyle.java
  app/src/main/java/com/isc/hermes/view/PolygonViewer.java
  app/src/main/java/com/isc/hermes/view/PolygonsViewer.java
Labels: bugfix

#269 Bug/ID-180-overlapping-action-messages-with-sign-up-button-in-user-re…
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
Labels: bugfix

#271 Bug/HotFix/TypeUserNullManagments
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/model/User/UserRepository.java
Labels: bug

#270 Start live time distance estimates on correct start button
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/model/navigation/LiveRouteEstimationsWorker.java
  app/src/main/java/com/isc/hermes/model/navigation/NavigationOrchestrator.java
  app/src/main/java/com/isc/hermes/model/navigation/NavigationRouteParser.java
  app/src/main/java/com/isc/hermes/model/navigation/NavigationTrackerTools.java
  app/src/main/java/com/isc/hermes/model/navigation/RouteDistanceHelper.java
  app/src/main/java/com/isc/hermes/model/navigation/RouteEstimatesManager.java
  app/src/main/java/com/isc/hermes/model/navigation/RoutesRepository.java
  app/src/main/java/com/isc/hermes/model/navigation/TrackRecoveryHandler.java
  app/src/main/java/com/isc/hermes/model/navigation/UserRouteTracker.java
  app/src/main/java/com/isc/hermes/model/navigation/UserRouteTrackerNotifier.java
  app/src/main/java/com/isc/hermes/model/navigation/events/Publisher.java
  app/src/main/java/com/isc/hermes/model/navigation/events/Subscriber.java
  app/src/main/java/com/isc/hermes/model/navigation/route_segments/RouteSegmentRecord.java
  app/src/main/java/com/isc/hermes/model/navigation/route_segments/RouteSegmentRecordBuilder.java
Labels: bugfix

#267 #211 Search Engine Allows Input of Words Exceeding 80 Characters
  app/src/main/java/com/isc/hermes/SearchViewActivity.java
Labels: bugfix

#252 BugFix/ID_181/FilterNumberOnChangeUserInfo
  app/src/main/java/com/isc/hermes/AccountInformation.java
Labels: bugfix

#275 Bug-272 / Start point should be always the current location after pressing navigation option
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
Labels: team-a, bugfix

#283 Bug/ID-534/The UserInformation section cannot be accessed due to problems with email validation when you are Admin user
  app/src/main/java/com/isc/hermes/EmailVerificationActivity.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/model/User/UserRepositoryUpdaterUsingDBRunnable.java
  app/src/main/java/com/isc/hermes/model/signup/SignUpTransitionHandler.java
  app/src/main/res/layout/activity_user_sign_up_completion_view.xml
Labels: bug, Severity 2

#261 Inconsistent functionality after login and log out
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/AboutUs.java
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/ActivitySelectRegion.java
  app/src/main/java/com/isc/hermes/AppManager.java
  app/src/main/java/com/isc/hermes/EmailVerificationActivity.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/OfflineMapsActivity.java
  app/src/main/java/com/isc/hermes/SearchViewActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
  app/src/main/java/com/isc/hermes/controller/IncidentsGetterController.java
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/MapWayPointController.java
  app/src/main/java/com/isc/hermes/controller/ShowTrafficController.java
  app/src/main/java/com/isc/hermes/controller/authentication/GoogleAuthentication.java
  app/src/main/java/com/isc/hermes/controller/incidents/IncidentPointVisualizationController.java
  app/src/main/java/com/isc/hermes/model/Utils/MapPolyline.java
  app/src/main/java/com/isc/hermes/model/signup/SignUpTransitionHandler.java
  app/src/main/java/com/isc/hermes/requests/geocoders/StreetValidator.java
  app/src/main/java/com/isc/hermes/utils/MarkerManager.java
  app/src/main/java/com/isc/hermes/utils/lifecycle/LastSessionTracker.java
  app/src/main/java/com/isc/hermes/view/IncidentViewNavigation.java
Labels: bugfix

#286 Bug/ID-535/Some transitions between authentication activities take a long time
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/AppManager.java
  app/src/main/java/com/isc/hermes/EmailVerificationActivity.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpContinueLikeGeneralUser.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpDeleteAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpOverwriteInformationAccount.java
  app/src/main/java/com/isc/hermes/database/ApiHandler.java
  app/src/main/java/com/isc/hermes/model/User/EmailVerificationRunnable.java
  app/src/main/java/com/isc/hermes/model/User/UserRelatedThreadManager.java
  app/src/main/java/com/isc/hermes/model/User/UserRepositoryCreatorUsingDBRunnable.java
  app/src/main/java/com/isc/hermes/model/User/UserRepositoryEditorUsingDBRunnable.java
  app/src/main/java/com/isc/hermes/model/User/UserRepositoryUpdaterUsingDBRunnable.java
  app/src/main/java/com/isc/hermes/model/signup/SignUpTransitionHandler.java
Labels: bug, Severity 2
