Repository CampusDelSaber/hermes, pull requests merged in 2023-06, with the labels that each got.

#1 ID-169[Feature] Map Creation
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/utils/MapConfigure.java
  app/src/main/java/com/isc/hermes/view/MapDisplay.java
  app/src/main/java/com/isc/hermes/view/delete.me
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/isc/hermes/ExampleUnitTest.java
  build.gradle
  gradle.properties
  settings.gradle
Labels: feature

#2 239feature/database connection
  app/.gitignore
  app/build.gradle
  app/src/main/java/com/isc/hermes/database/Connection.java
  app/src/main/java/com/isc/hermes/database/Hermesdb.java
  app/src/main/java/com/isc/hermes/database/collection/Collectible.java
  app/src/main/java/com/isc/hermes/database/collection/Incidents.java
  app/src/main/java/com/isc/hermes/database/schema/IncidentSchema.java
  app/src/test/java/com/isc/hermes/ExampleUnitTest.java
  app/src/test/java/com/isc/hermes/database/CollectionConnection.java
  app/src/test/java/com/isc/hermes/database/DatabaseConnection.java
Labels: feature

#3 ID-224[Feature] UI Sign Up creation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/res/drawable/baseline_arrow_back_ios_new_24.xml
  app/src/main/res/drawable/baseline_email_24.xml
  app/src/main/res/drawable/baseline_lock_24.xml
  app/src/main/res/drawable/baseline_supervised_user_circle_24.xml
  app/src/main/res/drawable/img_icon_google.png
  app/src/main/res/drawable/img_logo_app.png
  app/src/main/res/layout/activity_sign_up_view.xml
  app/src/main/res/values/Styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#7 Feature ID 161 - Get current location in real time
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/LocationPermissionsController.java
  app/src/main/java/com/isc/hermes/model/CurrentLocationModel.java
  app/src/main/java/com/isc/hermes/model/LocationPermissionsModel.java
  app/src/main/java/com/isc/hermes/utils/LocationListeningCallback.java
  app/src/main/java/com/isc/hermes/view/MapDisplay.java
  app/src/main/res/drawable/current_location_icon.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feature

#13 Feature/id 273/implementation about us view
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/AboutUs.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/res/drawable/backbutton.xml
  app/src/main/res/drawable/explore.xml
  app/src/main/res/drawable/map.xml
  app/src/main/res/drawable/warning.xml
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/values/about_Us_strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#24 Report incident feature without database implemented
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/delete.me
  app/src/main/java/com/isc/hermes/model/delete.me
  app/src/main/java/com/isc/hermes/utils/MapClickEventsManager.java
  app/src/main/java/com/isc/hermes/utils/MapConfigure.java
  app/src/main/java/com/isc/hermes/utils/MapReportIncidentClickEventListener.java
  app/src/main/java/com/isc/hermes/view/MapDisplay.java
  app/src/main/res/drawable/incident_icon.xml
  app/src/main/res/drawable/layer_icon.png
  app/src/main/res/drawable/report_incident_icon.xml
  app/src/main/res/drawable/speaker.png
  app/src/main/res/drawable/top_rounded_background.xml
  app/src/main/res/drawable/traffic_icon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/incident_form_fragment.xml
  app/src/main/res/layout/incident_spinner_items.xml
  app/src/main/res/values/strings.xml
Labels: feature

#29 Bug Fix: Hamburger button, Log Out and main window activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/controller/authentication/AuthenticationServices.java
  app/src/main/java/com/isc/hermes/controller/authentication/GoogleAuthentication.java
  app/src/main/java/com/isc/hermes/controller/authentication/IAuthentication.java
  app/src/main/res/drawable/img_burger_menu_button.png
  app/src/main/res/drawable/img_current_location_icon.png
  app/src/main/res/drawable/img_layer_icon.png
  app/src/main/res/drawable/img_speaker.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug

#32 Feature/ID-320/Read account information UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/res/drawable/baseline_arrow_back_ios_new_24.xml
  app/src/main/res/drawable/baseline_contacts_24.xml
  app/src/main/res/layout/activity_account_information.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: feature

#40 Feature/id 304/delete account UI (warning)
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/controller/DeleteAccountWarningDialog.java
  app/src/main/java/com/isc/hermes/controller/authentication/GoogleAuthentication.java
  app/src/main/java/com/isc/hermes/controller/authentication/IAuthentication.java
  app/src/main/res/drawable/popup_background.xml
  app/src/main/res/layout/delete_account_popup.xml
  app/src/main/res/values/strings.xml
Labels: feature

#43 Feature/id 177/incident storage
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
  app/src/main/java/com/isc/hermes/controller/MapController.java
  app/src/main/java/com/isc/hermes/database/IncidentsUploader.java
  app/src/main/java/com/isc/hermes/model/Utils/IncidentsUtils.java
  app/src/main/res/values/strings.xml
Labels: feature

#45 Feature/id 182/incident generation
  app/build.gradle
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/GenerateRandomIncidentController.java
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
  app/src/main/java/com/isc/hermes/controller/MapPolygonController.java
  app/src/main/java/com/isc/hermes/controller/MapWayPointController.java
  app/src/main/java/com/isc/hermes/controller/PolygonOptionsController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/controller/interfaces/MapClickConfigurationController.java
  app/src/main/java/com/isc/hermes/generators/CoordinateGen.java
  app/src/main/java/com/isc/hermes/generators/CoordinateParser.java
  app/src/main/java/com/isc/hermes/generators/LinestringGenerator.java
  app/src/main/java/com/isc/hermes/generators/PointGenerator.java
  app/src/main/java/com/isc/hermes/generators/PolygonGenerator.java
  app/src/main/java/com/isc/hermes/generators/Radium.java
  app/src/main/java/com/isc/hermes/model/incidents/Geometry.java
  app/src/main/java/com/isc/hermes/model/incidents/Incident.java
  app/src/main/java/com/isc/hermes/requests/geocoders/Geocoder.java
  app/src/main/java/com/isc/hermes/requests/geocoders/Geocoding.java
  app/src/main/java/com/isc/hermes/requests/geocoders/ReverseGeocoding.java
  app/src/main/java/com/isc/hermes/requests/geocoders/StreetValidator.java
  app/src/main/java/com/isc/hermes/utils/MapClickEventsManager.java
  app/src/main/java/com/isc/hermes/utils/MapConfigure.java
  app/src/main/java/com/isc/hermes/view/GenerateRandomIncidentView.java
  app/src/main/java/com/isc/hermes/view/MapDisplay.java
  app/src/main/java/com/isc/hermes/view/MapPolygonStyle.java
  app/src/main/res/drawable/img_icon_incident_generate.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/incident_generate_view.xml
  app/src/main/res/layout/natural_disaster_form_fragment.xml
  app/src/main/res/layout/waypoint_options_fragment.xml
  app/src/main/res/values/spinner_incident_generation.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/isc/hermes/generators/LinestringGeneratorTest.java
  app/src/test/java/com/isc/hermes/generators/PointGeneratorTest.java
  app/src/test/java/com/isc/hermes/generators/PolygonGeneratorTest.java
  app/src/test/java/com/isc/hermes/geocoders/GeocodingTest.java
  app/src/test/java/com/isc/hermes/geocoders/StreetValidatorTest.java
Labels: feature

#46 Delete Styles.xml
  app/src/main/res/values/Styles.xml
Labels: bug

#48 Feature/ID-333/functionality of the account information section
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUp.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpDeleteAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpEditAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/TypePopUp.java
  app/src/main/java/com/isc/hermes/controller/Utiils/ImageUtil.java
  app/src/main/java/com/isc/hermes/model/Utils/ImageUploaderToServerImgur.java
  app/src/main/java/com/isc/hermes/utils/MapConfigure.java
  app/src/main/res/drawable/baseline_save_24.xml
  app/src/main/res/drawable/popup_background.xml
  app/src/main/res/layout/activity_account_information.xml
  app/src/main/res/layout/popup.xml
  app/src/main/res/values/strings.xml
Labels: feature

#66 Fix/Data information Account
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/model/User.java
Labels: bug

#58 [Feature] ID198 - Implementation of waypoints with the searcher / Basic Filters
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SearchViewActivity.java
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/FilterController.java
  app/src/main/java/com/isc/hermes/controller/SearcherController.java
  app/src/main/java/com/isc/hermes/model/Searcher.java
  app/src/main/java/com/isc/hermes/utils/MapConfigure.java
  app/src/main/java/com/isc/hermes/utils/MarkerManager.java
  app/src/main/java/com/isc/hermes/utils/PlacesSearchedManager.java
  app/src/main/java/com/isc/hermes/utils/PlacesSearchedOnTheMap.java
  app/src/main/java/com/isc/hermes/utils/SearcherAdapter.java
  app/src/main/java/com/isc/hermes/utils/SearcherAdapterUpdater.java
  app/src/main/java/com/isc/hermes/utils/SearcherViewHolder.java
  app/src/main/java/com/isc/hermes/utils/SharedSearcherPreferencesManager.java
  app/src/main/java/com/isc/hermes/utils/WayPointClickListener.java
  app/src/main/java/com/isc/hermes/view/MapDisplay.java
  app/src/main/res/animator/click_animation.xml
  app/src/main/res/drawable/back_arrow.xml
  app/src/main/res/drawable/ic_go.xml
  app/src/main/res/drawable/ic_pin.xml
  app/src/main/res/drawable/img_filters_button.png
  app/src/main/res/drawable/radius_border.xml
  app/src/main/res/drawable/right_arrow.png
  app/src/main/res/drawable/selector_item.xml
  app/src/main/res/drawable/top_border.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_search_view.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/values/strings.xml
Labels: feature

#74 73 nothing happen when re entering to the map and clicking on it
  app/src/main/java/com/isc/hermes/MainActivity.java
Labels: bug

#82 Feature/ID-361/Delete account implementation using database
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUp.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpDeleteAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpEditAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpStyle.java
  app/src/main/java/com/isc/hermes/controller/PopUp/TypePopUp.java
  app/src/main/java/com/isc/hermes/database/AccountInfoManager.java
  app/src/main/java/com/isc/hermes/database/ApiHandler.java
  app/src/main/java/com/isc/hermes/database/ApiRequestHandler.java
  app/src/main/res/drawable/img_dark_style.jpg
  app/src/main/res/drawable/img_default_style.jpg
  app/src/main/res/drawable/img_right_arrow.png
  app/src/main/res/drawable/img_satellite_style.jpg
  app/src/main/res/drawable/popup_background.xml
  app/src/main/res/layout/customization_menu.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/popup.xml
Labels: feature

#75 Feature/id 357/two points naviagtion options
  app/src/main/java/com/isc/hermes/controller/FilterController.java
  app/src/main/java/com/isc/hermes/controller/MapWayPointController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/model/navigation/TransportationType.java
  app/src/main/res/drawable/bike_navoption_type.xml
  app/src/main/res/drawable/car_navoption_type.xml
  app/src/main/res/drawable/moto_navoption_type.xml
  app/src/main/res/drawable/walk_navoption_type.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/navigation_options.xml
  app/src/main/res/values/strings.xml
Labels: feature

#94 Bug-422/Database information not being retrieved in account information
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/database/AccountInfoManager.java
  app/src/main/java/com/isc/hermes/database/ApiRequestHandler.java
Labels: bug, Severity 2

#95 Feature/id 362/update account infomration db
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpOverwriteInformationAccount.java
  app/src/main/java/com/isc/hermes/database/AccountInfoManager.java
  app/src/main/java/com/isc/hermes/database/ApiHandler.java
  app/src/main/java/com/isc/hermes/database/ApiRequestHandler.java
  app/src/main/java/com/isc/hermes/model/User.java
Labels: feature

#100 Feature/ID-424/Validation if user is registered or is new user
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpDeleteAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpOverwriteInformationAccount.java
  app/src/main/java/com/isc/hermes/controller/Utiils/ImageUtil.java
  app/src/main/java/com/isc/hermes/database/AccountInfoManager.java
Labels: feature

#99 Feature/id 370/lazy loading natural disasters
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/MapPolygonController.java
  app/src/main/java/com/isc/hermes/controller/PolygonVisualizationController.java
  app/src/main/java/com/isc/hermes/controller/ViewIncidentsController.java
  app/src/main/java/com/isc/hermes/model/incidentsRequesting/NaturalDisasterRequesting.java
  app/src/main/java/com/isc/hermes/view/MapPolygonStyle.java
  app/src/main/res/drawable/eye_icon.png
  app/src/main/res/layout/activity_main.xml
Labels: feature

#102 Feature/ID-369/CRUD functions for user account data management
  app/build.gradle
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUp.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpDeleteAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpEditAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpOverwriteInformationAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpStyle.java
  app/src/main/java/com/isc/hermes/controller/PopUp/TypePopUp.java
  app/src/main/java/com/isc/hermes/controller/Utiils/ImageUtil.java
  app/src/main/java/com/isc/hermes/database/AccountInfoManager.java
  app/src/main/java/com/isc/hermes/database/ApiHandler.java
  app/src/main/java/com/isc/hermes/database/ApiRequestHandler.java
  app/src/main/java/com/isc/hermes/model/User.java
  app/src/main/res/drawable/img_dark_style.jpg
  app/src/main/res/drawable/img_default_style.jpg
  app/src/main/res/drawable/img_delete_icon_blue.png
  app/src/main/res/drawable/img_edit_icon_blue.png
  app/src/main/res/drawable/img_right_arrow.png
  app/src/main/res/drawable/img_satellite_style.jpg
  app/src/main/res/drawable/popup_background.xml
  app/src/main/res/layout/customization_menu.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/popup.xml
Labels: feature

#110 [Feature] ID178 - Advanced Search Filters
  app/build.gradle
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SpacingItemDecoration.java
  app/src/main/java/com/isc/hermes/controller/FilterCategoriesController.java
  app/src/main/java/com/isc/hermes/controller/FilterController.java
  app/src/main/java/com/isc/hermes/controller/GeocodeFiltersManager.java
  app/src/main/java/com/isc/hermes/model/CategoryFilter.java
  app/src/main/java/com/isc/hermes/model/Searcher.java
  app/src/main/java/com/isc/hermes/utils/CameraAnimator.java
  app/src/main/java/com/isc/hermes/utils/CategoryFilterAdapter.java
  app/src/main/java/com/isc/hermes/utils/CategoryFilterClickListener.java
  app/src/main/java/com/isc/hermes/utils/CategoryFilterViewHolder.java
  app/src/main/java/com/isc/hermes/utils/KeyBoardManager.java
  app/src/main/java/com/isc/hermes/utils/MarkerManager.java
  app/src/main/java/com/isc/hermes/utils/PlaceByTypeSearch.java
  app/src/main/java/com/isc/hermes/utils/PlacesType.java
  app/src/main/java/com/isc/hermes/utils/SearcherAdapterUpdater.java
  app/src/main/java/com/isc/hermes/utils/searcher/SearchPlacesListener.java
  app/src/main/java/com/isc/hermes/utils/searcher/SearchPlacesTask.java
  app/src/main/java/com/isc/hermes/view/FiltersView.java
  app/src/main/res/drawable/bar.png
  app/src/main/res/drawable/beach.png
  app/src/main/res/drawable/border_filter.xml
  app/src/main/res/drawable/cafe.png
  app/src/main/res/drawable/hotel.png
  app/src/main/res/drawable/library.png
  app/src/main/res/drawable/movie_theater.png
  app/src/main/res/drawable/museum.png
  app/src/main/res/drawable/navigation.png
  app/src/main/res/drawable/park.png
  app/src/main/res/drawable/restaurant.png
  app/src/main/res/drawable/selector_item_category.xml
  app/src/main/res/drawable/shopping_mall.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/filters_view.xml
  app/src/main/res/layout/item_filter_category.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#117 Feature/us 207/account verification
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/EmailVerificationActivity.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SearchViewActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/SpacingItemDecoration.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUp.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpContinueLikeGeneralUser.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpDeleteAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpOverwriteInformationAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpWarningIncorrectData.java
  app/src/main/java/com/isc/hermes/controller/authentication/AuthenticationServices.java
  app/src/main/java/com/isc/hermes/controller/authentication/GoogleAuthentication.java
  app/src/main/java/com/isc/hermes/controller/authentication/IAuthentication.java
  app/src/main/java/com/isc/hermes/database/AccountInfoManager.java
  app/src/main/java/com/isc/hermes/database/ApiHandler.java
  app/src/main/java/com/isc/hermes/database/ApiRequestHandler.java
  app/src/main/java/com/isc/hermes/database/SendEmailManager.java
  app/src/main/java/com/isc/hermes/database/VerificationCodesManager.java
  app/src/main/java/com/isc/hermes/model/User/User.java
  app/src/main/java/com/isc/hermes/model/User/UserRepository.java
  app/src/main/java/com/isc/hermes/model/Validator.java
  app/src/main/java/com/isc/hermes/model/VerificationCode.java
  app/src/main/java/com/isc/hermes/model/exceptions/CorruptedTokenException.java
  app/src/main/java/com/isc/hermes/model/exceptions/InvalidUserRoleException.java
  app/src/main/java/com/isc/hermes/model/signup/SignUpTransitionHandler.java
  app/src/main/java/com/isc/hermes/model/token/TokenGenerator.java
  app/src/main/java/com/isc/hermes/utils/CreateVerificationCode.java
  app/src/main/res/drawable/baseline_error_24.xml
  app/src/main/res/drawable/baseline_manage_accounts_24.xml
  app/src/main/res/drawable/email_icon.png
  app/src/main/res/layout/activity_mail_verification.xml
  app/src/main/res/layout/activity_sign_up_view.xml
  app/src/main/res/layout/offline_mode_settings_view.xml
  app/src/main/res/layout/popup.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/isc/hermes/model/user/UserRolesTest.java
Labels: feature

#121 Bug #443 - Advanced filters are not shown in the application
  app/src/main/java/com/isc/hermes/controller/FilterCategoriesController.java
  app/src/main/res/layout/activity_main.xml
Labels: bug, Severity 3

#125 Developers want to have a CI/CD workflow
  .github/workflows/apk_build.yml
  app/build.gradle
  app/sign_keys/debug.keystore
  build.gradle
  gradle.properties
  scripts/check_env.sh
  settings.gradle
Labels: task

#129 solve bug #432
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/controller/authentication/GoogleAuthentication.java
  app/src/main/java/com/isc/hermes/controller/authentication/IAuthentication.java
  app/src/main/java/com/isc/hermes/model/Utils/DataAccountOffline.java
  app/src/main/java/com/isc/hermes/utils/offline/NetworkManager.java
Labels: bug, Severity 2

#118 Feature/ID-418/Task-420/DropDown Menu
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/res/drawable/burger_button.xml
  app/src/main/res/drawable/icon_button_logout.png
  app/src/main/res/drawable/map_button_icon.png
  app/src/main/res/drawable/offline_button_icon.png
  app/src/main/res/drawable/third_dimension_button_icon.png
  app/src/main/res/drawable/traveler_button_icon.png
  app/src/main/res/drawable/user_button_icon.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/lateral_dropdown_header.xml
  app/src/main/res/menu/lateral_dropdown_menu.xml
  app/src/main/res/values/strings.xml
Labels: feature

#133 Task/id 245/mark start end point_Transportation Type buttons functionality
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/MapWayPointController.java
  app/src/main/java/com/isc/hermes/controller/NavigationDirectionController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
Labels: task

#135 Task/id 373/enhance walkable bidirectional graph
  app/src/main/java/com/isc/hermes/controller/GraphController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/test/java/com/isc/hermes/utils/DijkstraAlgorithmRealTest.java
  app/src/test/java/com/isc/hermes/utils/DijkstraAlgorithmTest.java
Labels: task

#149 Bug/id 461/Improve the main screen search engine
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: bug, Severity 3

#96 Task/id 421/natural disasters storage database
  .github/workflows/apk_build.yml
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/GenerateRandomIncidentController.java
  app/src/main/java/com/isc/hermes/controller/IncidentFormController.java
  app/src/main/java/com/isc/hermes/controller/MapPolygonController.java
  app/src/main/java/com/isc/hermes/controller/PolygonOptionsController.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpOverwriteInformationAccount.java
  app/src/main/java/com/isc/hermes/controller/TrafficAutomaticFormController.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/database/AccountInfoManager.java
  app/src/main/java/com/isc/hermes/database/IncidentsUploader.java
  app/src/main/java/com/isc/hermes/model/SaveProfileImage.java
  app/src/main/res/layout/activity_account_information.xml
  app/src/main/res/layout/activity_mail_verification.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/natural_disaster_form_fragment.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: task

#148 Feature/id 351/graph construction from streets
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/controller/CurrentLocationController.java
  app/src/main/java/com/isc/hermes/controller/GraphController.java
  app/src/main/java/com/isc/hermes/controller/InfoRouteController.java
  app/src/main/java/com/isc/hermes/controller/MapWayPointController.java
  app/src/main/java/com/isc/hermes/controller/NavigationDirectionController.java
  app/src/main/java/com/isc/hermes/controller/NavigationOptionsController.java
  app/src/main/java/com/isc/hermes/controller/offline/OfflineDataRepository.java
  app/src/main/java/com/isc/hermes/model/CurrentLocationModel.java
  app/src/main/java/com/isc/hermes/model/Utils/MapPolyline.java
  app/src/main/java/com/isc/hermes/model/graph/Graph.java
  app/src/main/java/com/isc/hermes/requests/overpass/IntersectionRequest.java
  app/src/main/java/com/isc/hermes/requests/overpass/WayRequest.java
  app/src/main/java/com/isc/hermes/utils/DijkstraAlgorithm.java
  app/src/main/java/com/isc/hermes/utils/LocationListeningCallback.java
  app/src/main/res/layout/loader_route_dialog.xml
  app/src/test/java/com/isc/hermes/utils/DijkstraAlgorithmRealTest.java
  app/src/test/java/com/isc/hermes/utils/DijkstraAlgorithmTest.java
Labels: feature

#155 Feature/ID-469/Enable and disable features depending on user type
  app/src/main/java/com/isc/hermes/AboutUs.java
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/OfflineMapsActivity.java
  app/src/main/java/com/isc/hermes/SearchViewActivity.java
  app/src/main/java/com/isc/hermes/SignUpActivityView.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUp.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpContinueLikeGeneralUser.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpDeleteAccount.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpWarningIncorrectData.java
  app/src/main/java/com/isc/hermes/controller/PopUp/ProgressDialogManager.java
  app/src/main/java/com/isc/hermes/controller/PopUp/TextInputPopup.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/model/User/TypeUser.java
  app/src/main/java/com/isc/hermes/model/signup/SignUpTransitionHandler.java
  app/src/main/java/com/isc/hermes/view/GenerateRandomIncidentView.java
  app/src/main/java/com/isc/hermes/view/IncidentViewNavigation.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_account_information.xml
Labels: feature

#158 Feature/id 468/user registration pop ups
  app/src/main/java/com/isc/hermes/MainActivity.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpWarningUpdateUserType.java
  app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java
  app/src/main/java/com/isc/hermes/view/GenerateRandomIncidentView.java
Labels: feature

#150 Bug/id 444/updating the role in the account information
  app/src/main/java/com/isc/hermes/AccountInformation.java
  app/src/main/java/com/isc/hermes/EmailVerificationActivity.java
  app/src/main/java/com/isc/hermes/UserSignUpCompletionActivity.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpContinueLikeGeneralUser.java
  app/src/main/java/com/isc/hermes/controller/PopUp/PopUpOverwriteInformationAccount.java
  app/src/main/java/com/isc/hermes/model/User/User.java
  app/src/main/java/com/isc/hermes/model/signup/SignUpTransitionHandler.java
  app/src/main/res/layout/activity_account_information.xml
Labels: bug, Severity 2
